#!/bin/bash


WORKDIR=/Users/px54/Documents/TB_software/manuscript_test/gisaid_23Oct_24Mar11/run
CODEDIR=/Users/px54/Documents/TB_software/V2_code/codes


## Network was generated by other programs
## Run networkgenerator

python network_generator.py -popsize 12907 -wkdir ${WORKDIR} \
	-method user_input -path_network /Users/px54/Documents/TB_software/manuscript_test/gisaid_23Oct_24Mar11/contact_network_generated


python seed_generator.py -method user_input -wkdir ${WORKDIR} -seed_size 16 \
	-seed_vcf /Users/px54/Documents/TB_software/manuscript_test/gisaid_23Oct_24Mar11/merged_seeds_remaned_filtered.vcf


python genetic_effect_generator.py -wkdir ${WORKDIR} -method user_input -trait_n 1 0 \
	-effsize_path /Users/px54/Documents/TB_software/manuscript_test/gisaid_23Oct_24Mar11/causal_gene_info.csv

#python seed_host_matcher.py -method randomly_generate -wkdir ${WORKDIR} -n_seed 16

python seed_host_matcher.py -method randomly_generate -wkdir ${WORKDIR} -n_seed 16 #\
#	-match_scheme '{"1": "Ranking"}' -match_scheme_param '{"1": 2}'


python outbreak_simulator.py -config ${WORKDIR}/test_config.json


